# Generated by Django 2.1 on 2019-09-04 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190904_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_html',
            field=models.TextField(editable=False, verbose_name='正文html代码'),
        ),
    ]
