# Generated by Django 2.1 on 2019-09-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190904_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_md',
            field=models.BooleanField(default=True, verbose_name='markdown语法'),
        ),
    ]
